from prediction_engine import predict, get_team_ranking, get_team_star_impact, get_head_to_head, get_team_stats

ta = "Sweden"
tb = "Poland"

r = predict(ta, tb)
stats_a = get_team_stats(ta)
stats_b = get_team_stats(tb)
h2h = get_head_to_head(ta, tb)
stars_a = get_team_star_impact(ta)
stars_b = get_team_star_impact(tb)

print("=== " + ta + " vs " + tb + " DIAGNOSTIC ===")
print()
print("RESULT: " + str(r["team_a_win"]) + "% | " + str(r["draw"]) + "% | " + str(r["team_b_win"]) + "%")
print("Lambdas: " + str(r["team_a_lambda"]) + " vs " + str(r["team_b_lambda"]))
print()
print("--- Rankings ---")
print(ta + ": FIFA #" + str(get_team_ranking(ta)))
print(tb + ": FIFA #" + str(get_team_ranking(tb)))
print()
print("--- Form (attack/defense) ---")
print(ta + ": attack=" + str(round(stats_a["attack"], 3)) + " defense=" + str(round(stats_a["defense"], 3)))
print(tb + ": attack=" + str(round(stats_b["attack"], 3)) + " defense=" + str(round(stats_b["defense"], 3)))
print(ta + ": weighted_gf=" + str(round(stats_a["weighted_gf"], 3)) + " weighted_ga=" + str(round(stats_a["weighted_ga"], 3)))
print(tb + ": weighted_gf=" + str(round(stats_b["weighted_gf"], 3)) + " weighted_ga=" + str(round(stats_b["weighted_ga"], 3)))
print()
print("--- Star Players ---")
print(ta + ": " + str(stars_a["players"][:5]) + " boost=" + str(stars_a["attack"]))
print(tb + ": " + str(stars_b["players"][:5]) + " boost=" + str(stars_b["attack"]))
print()
print("--- Head-to-Head (last 8) ---")
print("Matches: " + str(h2h["matches"]))
print(ta + " wins: " + str(h2h.get("wins_a", 0)))
print(tb + " wins: " + str(h2h.get("wins_b", 0)))
print("Draws: " + str(h2h.get("draws", 0)))
print("H2H factor " + ta + ": " + str(h2h.get("factor_a", 1.0)))
print("H2H factor " + tb + ": " + str(h2h.get("factor_b", 1.0)))
print()
print("--- Match Type ---")
print(r["match_type"])
print("Rank gap: " + str(r["rank_gap"]))
print()
print("--- Top Scores ---")
for s in r["top_scores"][:6]:
    print("  " + str(s))
